# Generated by Django 4.1.7 on 2023-03-15 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tris', '0004_food'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='Name',
            field=models.TextField(default=0),
        ),
    ]
